In [8]:
import numpy as np
from classes import *

# Overall Notes
* Have a variable that is our final accepting date for new brackets, then use this to generate the bracket data only once and then never go through that code again. Would this be faster than reading a text or xcel file?
* Have the data be generated once a day and not have to regenerate. Updating of new data is trigger by the first user who accesses the page every day

My thinking is that the data for each page is pregenerated daily?

# Define Bracket Class
* Name
* Team for each series
* Points Aquired
* Points Possible
* Total Points Possible


In [2]:
class Bracket:
  points_aquired = 0
  points_potential = 0
  points_totalPossible = 380  
  def __init__(self, name, winners):
    self.name = name
    self.seriesWinners = winners
  def calcPoints(self,SERIES,TEAMS):
      pass

# Define Series Class
Each series has 
* Number
* Home Team
* Away Team
* Score (I had this as its own .m file)
* Home Wins
* Away Wins
* SeriesDep (Does this series depend on a series from a previous round)
* isMatchupSet
* 7 Games
* Dates for each Game
* isComplete
* Winner
* HomePrevSeries (This was used to grey out teams that lost)
* AwayPrevSeries (This was used to grey out teams that lost)

In the matlab code, I had another variable called round complete. This variable saved if a round was complete or not. This in turn allowed parts of the code to be skipped so less calculations needed to be preformed. I can probably do this differently.

**Should there be a Round Class?**


In [3]:
class Series:
  number = 0
  HomeTeam = ''
  AwayTeam = ''
  Score = np.full((2,7),np.nan)
  HomeWins = 0
  AwayWins = 0
  SeriesDep = np.zeros((1,2))
  isMatchupSet = False
  isComplete = False
  Winner = ''
  HomePreviousSeries = 0
  AwayPreviousSeries = 0

  def __init__(self,number):
    self.number = number
    
  def updateScore(self,gameScore):
    self.Score = gameScore

 # Define Team Class

 Each Team has
 * Name
 * BackgroundColor
 * TextColor
 * DivisionRank
 * RegularSeasonRank
 * isEliminated

In [4]:
class Team:
  isEliminated = False
  #BackgroundColor = [0,0,0]
  #TextColor = [0,0,0]
  def __init__(self,name,DivisionRank,RegularSeasonRank):
    self.name = name
    self.DivisionRank = DivisionRank
    self.RegularSeasonRank = RegularSeasonRank

  def elimFunc(self):
    self.isEliminated = True


# Code Logic
Initialize
* Initialize/Save Bracket choices
* Initialize Series Data
* Initialize Team Data

Update Functions:
* Update Series from scores (How to create source for scores is still TBD)
* Update Master Bracket
* Update Individual Scores
* Update Graphics(Don't know how exactly we'll do this)

Update should only occur once per day(or once after a game is completed). People who access the site shouldn't have to wait for the code to run every time the load a page. Page data should be at minimum updated early morning the day after a game.

In [5]:
## Test Bracket
#TylerBracket = Bracket('Tyler',['Avalanche','Wild','Flames','Oilers','Panthers','Maple Leafs','Hurricanes','Penguins','Avalanche','Flames','Panthers','Hurricanes','Avalanche','Hurricanes','Hurricanes'])
#print(TylerBracket.name)
#print(TylerBracket.seriesWinners)
#print(TylerBracket.seriesWinners[1])

## Test Series
#Series1 = Series(1)
#print(Series1.number)
#print(Series1.HomeTeam)

## Test Team
# Hurricanes = Team('Hurricanes',1,3)
# print(Hurricanes.name)
# print(Hurricanes.isEliminated)
# Hurricanes.elimFunc()
# print(Hurricanes.isEliminated)


In [6]:
## Initialize brackets
# This would be read in by Corey's code (frontend)
brackets = []
#                                   ['Series1','Series2','Series3','Series4','Series5','Series6'   ,'Series7'   ,'Series8' ,'Series9'  ,'Series10','Series11' ,'Series12'  ,'Series13' ,'Series14'   ,'Series15'  ]
brackets.append( Bracket('Lydia'   ,['Avalanche','Blues','Flames','Oilers','Panthers','Maple Leafs','Bruins'    ,'Penguins','Avalanche','Flames','Maple Leafs','Bruins'    ,'Avalanche','Maple Leafs','Avalanche'  ]) )
brackets.append( Bracket('Tyler'   ,['Avalanche','Wild' ,'Flames','Oilers','Panthers','Maple Leafs','Hurricanes','Penguins','Avalanche','Flames','Panthers'   ,'Hurricanes','Avalanche','Hurricanes' ,'Hurricanes' ]) )
brackets.append( Bracket('Rob'     ,['Avalanche','Blues','Flames','Oilers','Panthers','Lightning'  ,'Hurricanes','Penguins','Avalanche','Flames','Panthers'   ,'Hurricanes','Avalanche','Panthers'   ,'Avalanche'  ]) )
brackets.append( Bracket('Allie'   ,['Avalanche','Wild' ,'Flames','Oilers','Capitals','Maple Leafs','Hurricanes','Penguins','Avalanche','Flames','Maple Leafs','Hurricanes','Avalanche','Maple Leafs','Maple Leafs']) )
brackets.append( Bracket('Xander'  ,['Avalanche','Blues','Flames','Kings' ,'Capitals','Lightning'  ,'Hurricanes','Penguins','Avalanche','Kings' ,'Capitals'   ,'Penguins'  ,'Avalanche','Penguins'   ,'Penguins'   ]) )
brackets.append( Bracket('Caroline',['Avalanche','Blues','Flames','Kings' ,'Capitals','Maple Leafs','Hurricanes','Rangers' ,'Avalanche','Kings' ,'Maple Leafs','Hurricanes','Avalanche','Hurricanes' ,'Avalanche'  ]) )
brackets.append( Bracket('Jordan'  ,['Avalanche','Wild' ,'Flames','Kings' ,'Panthers','Lightning'  ,'Hurricanes','Rangers' ,'Wild'     ,'Flames','Lightning'  ,'Hurricanes','Wild'     ,'Hurricanes' ,'Wild'       ]) )
brackets.append( Bracket('Daniel'  ,['Avalanche','Wild' ,'Stars' ,'Kings' ,'Panthers','Maple Leafs','Hurricanes','Penguins','Wild'     ,'Kings' ,'Panthers'   ,'Penguins'  ,'Wild'     ,'Panthers'   ,'Wild'       ]) )
brackets.append( Bracket('Isabella',['Avalanche','Wild' ,'Flames','Kings' ,'Capitals','Maple Leafs','Hurricanes','Rangers' ,'Avalanche','Flames','Maple Leafs','Hurricanes','Avalanche','Hurricanes' ,'Avalanche'  ]) )
brackets.append( Bracket('Sarah'   ,['Avalanche','Blues','Flames','Oilers','Panthers','Lightning'  ,'Hurricanes','Rangers' ,'Avalanche','Flames','Panthers'   ,'Hurricanes','Avalanche','Panthers'   ,'Avalanche'  ]) )
brackets.append( Bracket('Gus'     ,['Avalanche','Blues','Flames','Oilers','Panthers','Lightning'  ,'Bruins'    ,'Rangers' ,'Avalanche','Flames','Panthers'   ,'Rangers'   ,'Avalanche','Panthers'   ,'Avalanche'  ]) )
brackets.append( Bracket('Allison' ,['Avalanche','Wild' ,'Stars' ,'Oilers','Capitals','Maple Leafs','Bruins'    ,'Penguins','Avalanche','Stars' ,'Capitals'   ,'Bruins'    ,'Avalanche','Capitals'   ,'Avalanche'  ]) )
brackets.append( Bracket('Megan'   ,['Avalanche','Blues','Stars' ,'Oilers','Capitals','Maple Leafs','Hurricanes','Penguins','Avalanche','Oilers','Maple Leafs','Penguins'  ,'Avalanche','Penguins'   ,'Avalanche'  ]) )
brackets.append( Bracket('Corey'   ,['Avalanche','Wild' ,'Stars' ,'Kings' ,'Capitals','Lightning'  ,'Hurricanes','Rangers' ,'Avalanche','Stars' ,'Lightning'  ,'Hurricanes','Stars'    ,'Lightning'  ,'Lightning'  ]) )
brackets.append( Bracket('Felix'   ,['Avalanche','Wild' ,'Stars' ,'Oilers','Capitals','Maple Leafs','Hurricanes','Penguins','Avalanche','Oilers','Maple Leafs','Penguins'  ,'Oilers'   ,'Penguins'   ,'Oilers'     ]) )
brackets.append( Bracket('Jackson' ,['Avalanche','Wild' ,'Flames','Oilers','Panthers','Maple Leafs','Hurricanes','Rangers' ,'Avalanche','Flames','Panthers'   ,'Hurricanes','Avalanche','Panthers'   ,'Avalanche'  ]) )
brackets.append( Bracket('Mike'    ,['Avalanche','Wild' ,'Flames','Oilers','Panthers','Lightning'  ,'Hurricanes','Rangers' ,'Wild'     ,'Flames','Panthers'   ,'Hurricanes','Flames'   ,'Panthers'   ,'Panthers'   ]) )

print(brackets[1].name)
print(brackets[1].seriesWinners)
print(brackets[1].seriesWinners[14])

Tyler
['Avalanche', 'Wild', 'Flames', 'Oilers', 'Panthers', 'Maple Leafs', 'Hurricanes', 'Penguins', 'Avalanche', 'Flames', 'Panthers', 'Hurricanes', 'Avalanche', 'Hurricanes', 'Hurricanes']
Hurricanes


In [7]:
## Initialize Series Data
series = []

for i in range(15):
  #print(i)
  series.append( Series(i+1) )

# Set the first round
# Series 1
i = 0
series[i].HomeTeam = 'Avalanche'
series[i].AwayTeam = 'Predators'
series[i].HomePreviousSeries = 1
series[i].AwayPreviousSeries = 2
series[i].isMatchupSet = True

# Series 2
i = i+1
series[i].HomeTeam = 'Wild'
series[i].AwayTeam = 'Blues'
series[i].HomePreviousSeries = 3
series[i].AwayPreviousSeries = 4
series[i].isMatchupSet = True

# Series 3
i = i+1
series[i].HomeTeam = 'Flames'
series[i].AwayTeam = 'Stars'
series[i].HomePreviousSeries = 5
series[i].AwayPreviousSeries = 6
series[i].isMatchupSet = True

# Series 4
i = i+1
series[i].HomeTeam = 'Oilers'
series[i].AwayTeam = 'Kings'
series[i].HomePreviousSeries = 7
series[i].AwayPreviousSeries = 8
series[i].isMatchupSet = True

# Series 5
i = i+1
series[i].HomeTeam = 'Panthers'
series[i].AwayTeam = 'Capitals'
series[i].HomePreviousSeries = 1
series[i].AwayPreviousSeries = 2
series[i].isMatchupSet = True

# Series 6
i = i+1
series[i].HomeTeam = 'Maple Leafs'
series[i].AwayTeam = 'Lightning'
series[i].HomePreviousSeries = 1
series[i].AwayPreviousSeries = 2
series[i].isMatchupSet = True

# Series 7
i = i+1
series[i].HomeTeam = 'Hurricanes'
series[i].AwayTeam = 'Bruins'
series[i].HomePreviousSeries = 1
series[i].AwayPreviousSeries = 2
series[i].isMatchupSet = True

# Series 8
i = i+1
series[i].HomeTeam = 'Rangers'
series[i].AwayTeam = 'Penguins'
series[i].HomePreviousSeries = 1
series[i].AwayPreviousSeries = 2
series[i].isMatchupSet = True

######################################
# Set Series 9-15 dependencies
# Series 9
i = i+1
series[i].dependencies = np.array([[1,2]])

# Series 10
i = i+1
series[i].dependencies = np.array([[3,4]])

# Series 11
i = i+1
series[i].dependencies = np.array([[5,6]])

# Series 12
i = i+1
series[i].dependencies = np.array([[7,8]])

# Series 13
i = i+1
series[i].dependencies = np.array([[9,10]])

# Series 14
i = i+1
series[i].dependencies = np.array([[11,12]])

# Series 15
i = i+1
series[i].dependencies = np.array([[13,14]])

######################################
print(series[6].number)
print(series[6].HomeTeam)

7
Hurricanes


In [8]:
## Initialize Team Data
# I think this will have to be hard-coded
teams = []

teams.append(Team('Avalanche'  ,1,2 ))
teams.append(Team('Predators'  ,5,16))
teams.append(Team('Wild'       ,2,5 ))
teams.append(Team('Blues'      ,4,9 ))
teams.append(Team('Flames'     ,1,6 ))
teams.append(Team('Stars'      ,4,15))
teams.append(Team('Oilers'     ,2,11))
teams.append(Team('Kings'      ,3,14))
teams.append(Team('Panthers'   ,1,1 ))
teams.append(Team('Capitals'   ,4,13))
teams.append(Team('Maple Leafs',2,4 ))
teams.append(Team('Lightning'  ,4,8 ))
teams.append(Team('Hurricanes' ,1,3 ))
teams.append(Team('Bruins'     ,4,10))
teams.append(Team('Rangers'    ,2,7 ))
teams.append(Team('Penguins'   ,3,12))

print(teams[0].isEliminated)
print(teams[1].isEliminated)
teams[1].elimFunc()
print(teams[0].isEliminated)
print(teams[1].isEliminated)

False
False
False
True


Input the scores for the games

In [9]:
# scores_all = np.ndarray(shape=(2,7,15), dtype=int)
scores_all = np.zeros((15,2,7),order='F')
print(scores_all)
scores_all.fill(0)
# print(scores_all)

# Series 1 Avs/Preds
# scores_all[:,:,0]
test = np.array([[2, 1, 3, 3, np.nan, np.nan, np.nan], #Preds
                     [7, 2, 7, 5, np.nan, np.nan, np.nan]])   # Avs
print('')
print(test)
print(test.shape)
print(scores_all.shape)

[[[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]]

[[ 2.  1.  3.  3. nan nan nan]
 [ 7.  2.  7.  5. nan nan nan]]
(2, 7)
(15, 2, 7)


In [10]:
# Series 1 Avs/Preds
scores_all[0,:,:] = np.array([
  [2, 1, 3, 3, np.nan, np.nan, np.nan],  #Preds
  [7, 2, 7, 5, np.nan, np.nan, np.nan]]) # Avs               

# Series 2 Wild/Blues
scores_all[1,:,:] = np.array([
    [4, 2, 1, 5, 5, 5, np.nan],  # Blues
    [0, 6, 5, 2, 2, 1, np.nan]]) # Wild

# Series 3 Flames/Stars
scores_all[2,:,:] = np.array([
  [0, 2, 4, 1, 1, 4, 2],    # Stars
  [1, 0, 2, 4, 3, 2, 3]])   # Flames
    

# Series 4 Oilers/Kings
scores_all[3,:,:] = np.array([
  [4, 0, 2, 4, 5, 2, 0],  # Kings
  [3, 6, 8, 0, 4, 4, 2]]) # Oilers
    

# Series 5 Panthers/Caps
scores_all[4,:,:] = np.array([
  [4, 1, 6, 2, 3, 3, np.nan],   # Caps
  [2, 5, 1, 3, 5, 4, np.nan]]) # Panthers
    

# Series 6 Leafs/Lightning
scores_all[5,:,:] = np.array([
  [0, 5, 2, 7, 3, 4, 2],  # Lightning
  [5, 3, 5, 3, 4, 3, 1]]) # Leafs
    

# Series 7 Canes/Bruins
scores_all[6,:,:] = np.array([
  [1, 2, 4, 5, 1, 5, 2],  # Bruins
  [5, 5, 2, 2, 5, 2, 3]]) # Canes
    

# Series 8 Rangers/Penguins
scores_all[7,:,:] = np.array([
  [4, 2, 7, 7, 3, 3, 3],  # Penguins
  [3, 5, 4, 2, 5, 5, 4]]) # Rangers
    

# Series 9 Avs/Blues
scores_all[8,:,:] = np.array([
  [2, 4, 2, 3, 5, 2, np.nan],  # Blues
  [3, 1, 5, 6, 4, 3, np.nan]]) # Avs
    

# Series 10 Flames/Oilers
scores_all[9,:,:] = np.array([
  [6, 5, 4, 5, 5, np.nan, np.nan],  # Oilers
  [9, 3, 1, 3, 4, np.nan, np.nan]]) # Flames
    

# Series 11 Panthers/Lightning
scores_all[10,:,:] = np.array([
  [4, 2, 5, 2, np.nan, np.nan, np.nan],  # Lightning
  [1, 1, 1, 0, np.nan, np.nan, np.nan]]) # Panthers
    

# Series 12 Hurricanes/Rangers
scores_all[11,:,:] = np.array([
  [1, 0, 3, 4, 1, 5, 6],  # Rangers
  [2, 2, 1, 1, 3, 2, 2]]) # Hurricanes
    

# Series 13 Avs/Oilers
scores_all[12,:,:] = np.array([
  [6, 0, 2, 5, np.nan, np.nan, np.nan],  # Oilers
  [8, 4, 4, 6, np.nan, np.nan, np.nan]]) # Avs
    

# Series 14 Rangers/Lightning
scores_all[13,:,:] = np.array([
  [2, 2, 3, 4, 3, 2, np.nan],  # Lightning
  [6, 3, 2, 1, 1, 1, np.nan]]) # Rangers
    

# Series 15 Avs/Lightning
scores_all[14,:,:] = np.array([
  [3, 0, 6, 2, 3, 1, np.nan],  # Lightning
  [4, 7, 2, 3, 2, 2, np.nan]]) # Avs
    
# print(scores_all)

for i in range(8):
  # print(i)
  series[i].updateScore(scores_all[i,:,:])
  # print(series[i].Score)
  # print('')

for i in range(15):
  print(series[i].Score)
  print('')

[[ 2.  1.  3.  3. nan nan nan]
 [ 7.  2.  7.  5. nan nan nan]]

[[ 4.  2.  1.  5.  5.  5. nan]
 [ 0.  6.  5.  2.  2.  1. nan]]

[[0. 2. 4. 1. 1. 4. 2.]
 [1. 0. 2. 4. 3. 2. 3.]]

[[4. 0. 2. 4. 5. 2. 0.]
 [3. 6. 8. 0. 4. 4. 2.]]

[[ 4.  1.  6.  2.  3.  3. nan]
 [ 2.  5.  1.  3.  5.  4. nan]]

[[0. 5. 2. 7. 3. 4. 2.]
 [5. 3. 5. 3. 4. 3. 1.]]

[[1. 2. 4. 5. 1. 5. 2.]
 [5. 5. 2. 2. 5. 2. 3.]]

[[4. 2. 7. 7. 3. 3. 3.]
 [3. 5. 4. 2. 5. 5. 4.]]

[[nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan]]

[[nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan]]

[[nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan]]

[[nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan]]

[[nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan]]

[[nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan]]

[[nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan]]



Now is the updateMasterBracket, which updates all the series and teams data